apiVersion: apps/v1
kind: Deployment
metadata:
  name: "myd"
  labels:
    app: myd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myd
  strategy:
    type: RollingUpdate
    rollingUpdate:
           maxSurge: 25%
           maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: myd
    spec:
      containers:
      - image: buddhi82/intern:latest
        name: intern
    
